### ISSUE TITLE
True color image preview does not work on Fedora.

### ISSUE THREAD

**Issue by vekin** [hut/ranger#104]
ranger version: 1.6.1, executed with python 2.7.5
Locale: en_US.UTF-8
Current file: /home/kevin/61zrgAs.png
Traceback (most recent call last):
  File "/home/kevin/ranger-1.6.1/ranger/core/main.py", line 133, in main
    fm.loop()
  File "/home/kevin/ranger-1.6.1/ranger/core/fm.py", line 303, in loop
    loader.work()
  File "/home/kevin/ranger-1.6.1/ranger/core/loader.py", line 374, in work
    self.fm.notify(err)
  File "/home/kevin/ranger-1.6.1/ranger/core/loader.py", line 368, in work
    next(item.load_generator)
  File "/home/kevin/ranger-1.6.1/ranger/core/loader.py", line 141, in generate
    stdout=PIPE, stderr=PIPE, stdin=stdin)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ranger crashed.  Please report this traceback at:
http://savannah.nongnu.org/bugs/?group=ranger&func=additem

I have installed the w3m-img package.
Images in w3m work.
"set preview_images true" is in .config/ranger/rc.conf
I ran ranger --copy-config=all
I tried export W3MIMGDISPLAY_PATH=/usr/libexec/w3m/w3mimgdisplay

**Comment by hut** [comment]
I'm closing this because it's an old issue which has not occured in a while and is most likely resolved by now.
