### ISSUE TITLE
UnicodeDecodeError with git repos with Unicode-char-contained path and space-contained filenames

### ISSUE THREAD

**Issue by alick** [hut/ranger#209]
Hi, I met a UnicodeDecodeError issue with ranger 1.6.1 for a while, and now I finally find a way to reproduce it reliably.

It happens with a git repo which has:
- a pathname containing non-ASCII characters, e.g. `/home/alick/test/café.git`
- a file with spaces in the name, e.g. `hi space`. The file should be untracked, or in staging area. (When it is committed, then no issue)

In such case, when I try to use ranger to inspect the repo (cd into that repo and `ranger .`), I get:

```
ranger version: 1.6.1, executed with python 2.7.5
Locale: zh_CN.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ranger/core/main.py", line 133, in main
    fm.loop()
  File "/usr/lib/python2.7/site-packages/ranger/core/fm.py", line 288, in loop
    self.enter_dir(self.thistab.path)
  File "/usr/lib/python2.7/site-packages/ranger/core/actions.py", line 450, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/lib/python2.7/site-packages/ranger/core/tab.py", line 141, in enter_dir
    self.assign_cursor_positions_for_subdirs()
  File "/usr/lib/python2.7/site-packages/ranger/core/tab.py", line 90, in assign_cursor_positions_for_subdirs
    path.move_to_obj(last_path)
  File "/usr/lib/python2.7/site-packages/ranger/container/directory.py", line 435, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python2.7/site-packages/ranger/container/directory.py", line 488, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python2.7/site-packages/ranger/container/directory.py", line 333, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python2.7/site-packages/ranger/container/directory.py", line 263, in load_bit_by_bit
    item.load_vcs(self)
  File "/usr/lib/python2.7/site-packages/ranger/container/fsobject.py", line 257, in load_vcs
    self.vcsfilestatus = self.vcs.get_file_status(self.path)
  File "/usr/lib/python2.7/site-packages/ranger/ext/vcs/vcs.py", line 253, in get_file_status
    sts = set(st for p, st in self.status.items()
  File "/usr/lib/python2.7/site-packages/ranger/ext/vcs/vcs.py", line 254, in <genexpr>
    if self._path_contains(path, os.path.join(self.root, p)))
  File "/usr/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

ranger crashed.  Please report this traceback at:
http://savannah.nongnu.org/bugs/?group=ranger&func=additem
```

And, when I use ranger to browse the outside (`ranger ~`), after I put the highlighted line to `test/` directory, the error message appears at the bottom line, and I cannot see **anything** in the `test/` directory! This is the most confusing and annoying side-effect to me.

**Comment by hut** [comment]
I managed to reproduce it, but I have no idea how to fix it. =S I don't understand why it tries to use the ascii codec instead of utf-8...

**Comment by tjanson** [comment]
I’ve had this problem on and off for at least a year, apparently depending on my Python version (i.e., it sometimes appears after updating Python – just as it has today).

I don’t think I’ve ever seen it triggered by a space, as @alick describes, but I can (currently) consistently reproduce it with umlauts:

```sh
mkdir täst
cd täst
touch anyname
git init
ranger .
```

which yields the following error (pretty much identical to above, but for completeness)

```
ranger version: 1.7.1, executed with python 2.7.10
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/fm.py", line 316, in loop
    self.enter_dir(self.thistab.path)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/actions.py", line 465, in enter_dir
    result = self.thistab.enter_dir(path, history=history)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/tab.py", line 141, in enter_dir
    self.assign_cursor_positions_for_subdirs()
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/tab.py", line 90, in assign_cursor_positions_for_subdirs
    path.move_to_obj(last_path)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/container/directory.py", line 516, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/container/directory.py", line 569, in load_content_once
    self.load_content(*a, **k)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/container/directory.py", line 401, in load_content
    for _ in self.load_generator:
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/container/directory.py", line 331, in load_bit_by_bit
    item.load_vcs(self)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/container/fsobject.py", line 302, in load_vcs
    self.vcsfilestatus = self.vcs.get_file_status(self.path)
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/ext/vcs/vcs.py", line 241, in get_file_status
    sts = set(st for p, st in self.status.items()
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/ext/vcs/vcs.py", line 242, in <genexpr>
    if self._path_contains(path, os.path.join(self.root, p)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 15: ordinal not in range(128)

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Workaround**: Simply renaming the folder (removing the umlaut) prevents the error.

Again, this problem has come and gone many times, which is curious. If I recall correctly, it sometimes went away simply by reinstalling Python and ranger (via Homebrew, i.e., `brew reinstall python ranger`). I suspect the answer is something very simple, e.g., adding a conversion as described in [this StackOverflow discussion](http://stackoverflow.com/a/21129492/3826702).

**Comment by tjanson** [comment]
Changing the offending line 242 in `ext/vcs/vcs.py` seems to fix this error:

```py
        # check if prel is a directory that contains some file in status
        prel = os.path.relpath(path, self.root)
        if os.path.isdir(path):
            sts = set(st for p, st in self.status.items()
                      # note the added `encode("utf-8")` here -------------v
                      if self._path_contains(path, os.path.join(self.root, p.encode("utf-8"))))
            for st in self.FILE_STATUS:
                if st in sts: return st
```

I’m not confident enough in my Python/encoding to submit this as a PR – I just followed some StackOverflow suggestion and it seems to work.
