### ISSUE TITLE
crash while copying filename from cifs share using shortcut 'yp'

### ISSUE THREAD

**Issue by Pi03k** [hut/ranger#216]
ranger version: 1.6.1, executed with python 3.4.1
Locale: None.None
Current file: /mnt/karczoch/Users/pmucko/klocwork/17_fm_rp1/69.bin.lzma
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 133, in main
fm.loop()
File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 314, in loop
ui.handle_input()
File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 208, in handle_input
self.handle_key(key)
File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 144, in handle_key
self.press(key)
File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 159, in press
quantifier=keybuffer.quantifier)
File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 169, in execute_console
escape=cmd.escape_macros_for_shell)
File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 184, in substitute_macros
macros = self._get_macros()
File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 243, in _get_macros
if tabdir.get_selection():
File "/usr/lib/python3.4/site-packages/ranger/container/directory.py", line 161, in get_selection
return [item for item in self.files if item.marked]
TypeError: 'NoneType' object is not iterable

I haven't tested it on local mount points. It happens randomly.

**Comment by Pi03k** [comment]
It happens also on git HEAD.
ranger version: 1.6.1, executed with python 3.4.2
Locale: None.None
Current file: /mnt/karczoch/Users/pmucko/blackbox3/9_reset_provider/69.bin.lzma
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 325, in loop
    ui.handle_input()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 213, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 149, in handle_key
    self.press(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 164, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 221, in execute_console
    escape=cmd.escape_macros_for_shell)
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 236, in substitute_macros
    macros = self._get_macros()
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 295, in _get_macros
    if tabdir.get_selection():
  File "/usr/lib/python3.4/site-packages/ranger/container/directory.py", line 189, in get_selection
    return [item for item in self.files if item.marked]
TypeError: 'NoneType' object is not iterable

**Comment by hut** [comment]
I pushed an update, can you try it with the current version?

**Comment by Pi03k** [comment]
It hasn't occured since your update. I consider it fixed. Thank you.
