### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by mortonfox** [hut/ranger#249]
In Python 2.6, sys.version_info is not a named tuple. The ranger source code uses sys.version_info.major in a number of places, so it fails with the following:

    Traceback (most recent call last):
    File "ranger.py", line 40, in <module>
        sys.exit(ranger.main())
    File "/tmp/ranger/ranger/core/main.py", line 15, in main
        from ranger.core.fm import FM
    File "/tmp/ranger/ranger/core/fm.py", line 16, in <module>
        from ranger.core.actions import Actions
    File "/tmp/ranger/ranger/core/actions.py", line 20, in <module>
        from ranger.ext.keybinding_parser import key_to_string, construct_keybinding
    File "/tmp/ranger/ranger/ext/keybinding_parser.py", line 8, in <module>
        PY3 = sys.version_info.major >= 3
    AttributeError: 'tuple' object has no attribute 'major'

**Comment by hut** [comment]
Sorry for missing that & thanks for reporting. Fixed =)
