### ISSUE TITLE
AttributeError: 'FM' object has no attribute 'env'  ranger crashed.

### ISSUE THREAD

**Issue by arkhan** [hut/ranger#297]
i'm installed the last version of ranger, emacs variant, when execute command M-x [compress](https://wiki.archlinux.org/index.php/Ranger#Compression), M-x [extracthere](https://wiki.archlinux.org/index.php/Ranger#Archive_extraction), get this error:
```python
ranger version: 1.7.0, executed with python 2.7.9
Locale: es_EC.UTF-8
Current file: /home/arkhan/1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib64/python2.7/site-packages/ranger/core/fm.py", line 346, in loop
    ui.handle_input()
  File "/usr/lib64/python2.7/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib64/python2.7/site-packages/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib64/python2.7/site-packages/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/console.py", line 172, in press
    if not self.fm.ui.press(key):
  File "/usr/lib64/python2.7/site-packages/ranger/gui/ui.py", line 162, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib64/python2.7/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib64/python2.7/site-packages/ranger/config/commands.py", line 720, in execute
    p(err)
  File "/usr/lib64/python2.7/site-packages/ranger/config/commands.py", line 713, in execute
    result = eval(code)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/console.py", line 365, in execute
    self.fm.execute_console(self.line)
  File "/usr/lib64/python2.7/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/home/arkhan/.config/ranger/commands.py", line 95, in execute
    cwd = self.fm.env.cwd
AttributeError: 'FM' object has no attribute 'env'
```python

**Comment by hut** [comment]
your commands.py is out of date, please update. If this is a custom command: change things like `self.fm.env.cwd` to `self.fm.thisdir`, `self.fm.env.cf` into `self.fm.thisfile`.

**Comment by arkhan** [comment]
ok thanks, the command: M-x [compress](https://wiki.archlinux.org/index.php/Ranger#Compression) it's works.

how to update this command: 
M-x [extracthere](https://wiki.archlinux.org/index.php/Ranger#Archive_extraction)
```python
class extracthere(Command):
    def execute(self):
        """ Extract copied files to current directory """
        copied_files = tuple(self.fm.env.copy)

        if not copied_files:
            return

        def refresh(_):
            cwd = self.fm.env.get_directory(original_path)
            cwd.load_content()

        one_file = copied_files[0]
        cwd = self.fm.env.cwd
        original_path = cwd.path
        au_flags = ['-X', cwd.path]
        au_flags += self.line.split()[1:]
        au_flags += ['-e']

        self.fm.env.copy.clear()
        self.fm.env.cut = False
        if len(copied_files) == 1:
            descr = "extracting: " + os.path.basename(one_file.path)
        else:
            descr = "extracting files from: " + os.path.basename(one_file.dirname)
        obj = CommandLoader(args=['aunpack'] + au_flags \
                + [f.path for f in copied_files], descr=descr)

        obj.signal_bind('after', refresh)
        self.fm.loader.add(obj)
```python

**Comment by hut** [comment]
Here's the old compatibility module: https://github.com/hut/ranger/blob/116d214e261b9e76a49411d65045f1a73efb1799/ranger/core/environment.py

There you can look up how to convert individual `self.fm.env` attributes. For example, to find out what `self.fm.env.copy` now is, look for `_get_copy` in the file (line 15). `_get_copy` is defined as
```python
return self.fm.copy_buffer
```
So just replace `self.fm.env.copy` with `self.fm.copy_buffer`. The same works for every attribute/method of `self.fm.env`.
