### ISSUE TITLE
:bulkrename expected str instance, bytes found

### ISSUE THREAD

**Issue by lapinskim** [hut/ranger#299]
After saving and exiting the first temp file with changed filenames no files are renamed and I get the following error:
```
ranger version: 1.7.0, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /home/maciek/test/c.out
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/console.py", line 172, in press
    if not self.fm.ui.press(key):
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 162, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 720, in execute
    p(err)
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 713, in execute
    result = eval(code)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/console.py", line 365, in execute
    self.fm.execute_console(self.line)
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 857, in execute
    script_content = "".join(script_lines)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by hut** [comment]
This works when you use python2, by the way
