### ISSUE TITLE
"TypeError" on data returned from external editor after "bulkrename"

### ISSUE THREAD

**Issue by lamarpavel** [hut/ranger#310]
When selecting multiple files and calling ```:bulkrename``` vim opens as expected and I can edit the text. However, on closing - when the data is returned, ranger spits out the error ```sequence item 0: expected str instance, bytes found```. Starting ranger with --debug reveals:

```
ranger version: 1.7.0, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /home/tmp/testfile.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 147, in handle_key
    self.press(key)
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 162, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 720, in execute
    p(err)
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 713, in execute
    result = eval(code)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/ranger/core/actions.py", line 183, in execute_console
    cmd_class(string, quantifier=quantifier).execute()
  File "/usr/lib/python3.4/site-packages/ranger/config/commands.py", line 857, in execute
    script_content = "".join(script_lines)
TypeError: sequence item 0: expected str instance, bytes found
```

I have no experience with Python, all I have tried so far was to use python2.7 rather than python3.4, as described in the [arch wiki](https://wiki.archlinux.org/index.php/Python#Python_2) but that was in vain.

In vim (and neovim) I have set fileencoding to latin1, ascii and utf-8 before saving but the result was the same. My version of ranger is 1.7.0-1 from the official arch repos.

**Comment by hut** [comment]
This is fixed in ranger-git and will be included in the next release.
