### ISSUE TITLE
Crash on cut, paste of symlinks

### ISSUE THREAD

**Issue by industrialzone** [hut/ranger#343]
I have been getting the below problem often when cutting and pasting (dd, pp) symlinks to directories on my external harddrive. Files that aren't symlinks do not seem to cause a problem. I'm not sure what that would have to do with it. I tested more, and it is not only symlinks to my external hdd, it is symlinks i in general that cause the problem. It seems to be a UI issue from the stack trace.

ranger version: 1.7.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /home/iijj/downloads/semillas/(2001) The Beach Boys - Pet Sounds (Remaster Stereo) [FLAC+.cue]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/statusbar.py", line 310, in _print_result
    self.color_at(0, 0, int(barwidth), ("in_statusbar", "loaded"))
  File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 67, in color_at
    self.win.chgat(y, x, wid, attr)
OverflowError: signed integer is greater than maximum

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues

**Comment by UnrealQuester** [comment]
I am unable to repdoduce the issue with the current master. Here is what I am doing:
- Create new directory in $HOME called foo
- Create a symlink that points to foo via `ln -s foo bar`
- Open ranger
- Cut symlink via dd
- Paste symlink into a different directory

**Comment by industrialzone** [comment]
Sorry, I should have closed this. The issue has not popped up since so I don't have more info to provide.

**Comment by industrialzone** [comment]
Sorry, I should have closed this. The issue has not popped up since.

**Comment by ald0n** [comment]
Got the same output with exactly the same case - cut/paste symlink. As a result it moved BUT converts into directory(?) with the same name and same files included in and symlink remained in the old place.

ranger version: 1.7.2, executed with python 3.4.5
Locale: en_US.UTF-8
Current file: /opt/oracle-jdk-bin-1.8.0.112
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib64/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib64/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib64/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib64/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib64/python3.4/site-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._print_result(self.result)
  File "/usr/lib64/python3.4/site-packages/ranger/gui/widgets/statusbar.py", line 310, in _print_result
    self.color_at(0, 0, int(barwidth), ("in_statusbar", "loaded"))
  File "/usr/lib64/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 67, in color_at
    self.win.chgat(y, x, wid, attr)
OverflowError: signed integer is greater than maximum

**Comment by sadid** [comment]
I had the same issue
the workflow was like this before crash:
1. Select two files from folder A using select (space) and `dd`
2. [instead of files] select the folder A instead using space and `dd`
3. Trying to paste folder A in another folder:
-------------------------
ranger version: 1.7.2, executed with python 3.5.2
Locale: en_US.UTF-8
Current file: /home/sadid/Desktop/zOrg/2Pr/Learning
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.5/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/statusbar.py", line 100, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.5/site-packages/ranger/gui/widgets/statusbar.py", line 310, in _print_result
    self.color_at(0, 0, int(barwidth), ("in_statusbar", "loaded"))
  File "/usr/lib/python3.5/site-packages/ranger/gui/curses_shortcuts.py", line 67, in color_at
    self.win.chgat(y, x, wid, attr)
OverflowError: signed integer is greater than maximum

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
-----------------------------------

**Comment by nfnty** [comment]
Update to version 1.8.0 and try again.

**Comment by sadid** [comment]
I can confirm that in the 1.8.0 version the problem has been resolved.
