### ISSUE TITLE
Crash on quit

### ISSUE THREAD

**Issue by ShionRyuu** [hut/ranger#347]
```bash
$ ranger
ranger version: 1.7.1, executed with python 2.7.6
Locale: zh_CN.UTF-8
Current file: /home/ryuu/app
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/fm.py", line 362, in loop
    self.image_displayer.quit()
  File "/usr/local/lib/python2.7/dist-packages/ranger/ext/img_display.py", line 135, in quit
    self.process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1556, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1546, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
[1]    13599 exit 1     TERM=xterm-256color ranger
```

**Comment by hut** [comment]
Fixed, thanks :)
