### ISSUE TITLE
Can not open ranger in gvim by ":!ranger".

### ISSUE THREAD

**Issue by Mizuchi** [hut/ranger#351]
Motivation: I am the author of vim-ranger and it's related to this issue: https://github.com/Mizuchi/vim-ranger/issues/6
System: Arch Linux
it works in the terminal (xterm), but when I run :!ranger in gvim I got such error:

```
ranger version: 1.7.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: /home/ytj/bin
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 8, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.default.Default object at 0xb69bb58c>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 29, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python3.4/site-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by hut** [comment]
I fixed this crash, but this doesn't solve your issue - ranger will still not work in gvim, because it doesn't seem to support any kind of programs using ncurses. For example, try running `:!top`, it will mess up the editor.

Instead I recommend using the patch from pull request #353 which opens a separate terminal for ranger.
