### ISSUE TITLE
xterm titlebar is not updated

### ISSUE THREAD

**Issue by hut** [hut/ranger#356]
Even when using `:set update_title true`, the titlebar of the xterm window is not updated.

**Comment by hut** [comment]
This is because the `xterm` terminfo file does not specify `hs` (short for "has statusline") as an available capability of xterm. See `infocmp xterm | grep hs`.

By setting the environment variable `TERM` to something like `xterm+sl`, the terminfo file will give ranger the needed information on how to set the title and everything should work out. You can test this with `TERM=xterm+sl ranger`.

Put `[ "$TERM" == "xterm" ] && export TERM=xterm+sl` in your ~/.bashrc (or whatever your shell uses) for a permanent fix, though I don't know about side effects of this.

**Comment by vejkse** [comment]
When I do `TERM=xterm+sl ranger`, I get:

```
ranger version: 1.7.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 8, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.default.Default object at 0x7f5a09316080>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 29, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python3.4/site-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

It seems to be due to the latest version of ncurses (6.0).

**Comment by NoSuck** [comment]
Try the following, code-tag-less worker of miracles:

infocmp xterm > togtfo
infocmp -0 xterm+sl | tail -n1 >> togtfo
tic togtfo

-----元のメッセージ-----
差出人: "vejkse" <notifications@github.com>
送信日時: ‎2015/‎09/‎29 5:41
宛先: "hut/ranger" <ranger@noreply.github.com>
CC: "NoSuck" <admin@nosuck.org>
件名: Re: [ranger] xterm titlebar is not updated (#356)

When I do TERM=xterm+sl ranger, I get:
ranger version: 1.7.1, executed with python 3.4.3
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 8, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.default.Default object at 0x7f5a09316080>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 29, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ranger/core/main.py", line 139, in main
    fm.loop()
  File "/usr/lib/python3.4/site-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.4/site-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 39, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.4/site-packages/ranger/gui/widgets/titlebar.py", line 151, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3.4/site-packages/ranger/gui/curses_shortcuts.py", line 57, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3.4/site-packages/ranger/ext/cached_function.py", line 10, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python3.4/site-packages/ranger/gui/colorscheme.py", line 66, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python3.4/site-packages/ranger/gui/color.py", line 38, in get_color
    curses.init_pair(size, fg, bg)
_curses.error: init_pair() returned ERR

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
It seems to be due to the latest version of ncurses (6.0).
