### ISSUE TITLE
Crashes on premature keypress

### ISSUE THREAD

**Issue by baskerville** [hut/ranger#357]
Pressing a key while the UI is loading crashes *ranger*:
```
ranger version: 1.6.1, executed with python 2.7.6
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "core/main.py", line 139, in main
    fm.loop()
  File "core/fm.py", line 318, in loop
    ui.handle_input()
  File "gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "gui/ui.py", line 145, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "gui/displayable.py", line 261, in press
    focused_obj.press(key)
  File "gui/widgets/console.py", line 173, in press
    self.type_key(key)
  File "gui/widgets/console.py", line 202, in type_key
    self.on_line_change()
  File "gui/widgets/console.py", line 418, in on_line_change
    if cmd and cmd.quick():
  File "api/commands.py", line 399, in quick
    return self._make_cmd().quick()
  File "config/commands.py", line 1053, in quick
    if self._count(move=asyoutype) == 1 and self.AUTO_OPEN in self.flags:
  File "config/commands.py", line 1118, in _count
    deq = deque(cwd.files)
TypeError: 'NoneType' object is not iterable
```

**Comment by eMPee584** [comment]
Just wanted to report this exact same crash. It happens f.e. when starting to filter-as-you-type while a huge directory's file entries are being parsed. To reproduce, clearing the in-memory filesystem cache by `echo 3 > /proc/sys/vm/drop_caches` might be useful :)
