### ISSUE TITLE
Arch based system, starting ranger fails

### ISSUE THREAD

**Issue by gdane195** [hut/ranger#407]
Hi All, could someone please explain this one to me. I have used Ranger for years...and then in the last week I can't run it...

~ #> ranger
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 371, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ranger", line 39, in <module>
    sys.exit(ranger.main())
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 16, in main
    from ranger.core.fm import FM
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 11, in <module>
    import socket
  File "/usr/lib/python3.5/socket.py", line 73, in <module>
    IntEnum._convert(
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 373, in __getattr__
    raise AttributeError(name)
AttributeError: _convert

**Comment by gdane195** [comment]
Sorry, I had forgoten I had my PYTHONPATH set to

PYTHONPATH=/usr/lib/python2.7/site-packages

I removed it and all is good.
