### ISSUE TITLE
video preview thumbnail cache

### ISSUE THREAD

**Issue by dquinton** [hut/ranger#427]
I've got video/image previews just fine, ranger from git today.

I use the key mapping
`map zx  toggle_option preview_images`
to toggle inline preview so that I can also use the mediainfo display.

problem: when I toggle OFF image preview of videos (to view data) after already getting image previews of them, and hit Ctrl-r to refresh, the video image still shows, mediainfo output does not display, - it seems that the video thumbnail is still held in the ranger preview cache.

It's OK for image files, toggle OFF, Ctrl-r, and info is displayed - but I understand that ffmpegthumbnailer requires -i and -o  to work, hence the `"$cached"` ?

so how can the thumbnail cache be cleared when I toggle OFF?

**Comment by hut** [comment]
cc @GermainZ

**Comment by GermainZ** [comment]
Something like this could work in actions.py (untested):

````py
def on_preview_images_change(signal):
    if signal.value is not "false":
        return None
    for data in self.previews:
        if 'imagepreview' in data:
            try:
                del data
            except:
                pass

SignalDispatcher().signal_bind("setopt.preview_images", on_preview_images_change)
````

Probably in Actions' \__init__() unless I'm missing something about signals.

Basically deletes cached previews for images (from ranger's "memory", not from the disk) when image previews are turned off.

**Comment by dquinton** [comment]
Sorry, but ranger fails to start with that code added to actions.py...

`Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 39, in <module>
    sys.exit(ranger.main())
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 16, in main
    from ranger.core.fm import FM
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/fm.py", line 16, in <module>
    from ranger.core.actions import Actions
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/actions.py", line 1360, in <module>
    SignalDispatcher().signal_bind("setopt.preview_images", on_preview_images_change)
NameError: name 'SignalDispatcher' is not defined'

**Comment by GermainZ** [comment]
That's because the import is missing but it probably won't work without a few minor changes anyway. I haven't had the time to test it yet but will send a pull request when I do.

**Comment by sharethewisdom** [comment]
Hi, I've written a command that allows me to use `self.quantifier` along with the so-called *gravity* type from [wand.image](http://docs.wand-py.org/en/0.4.2/) to quickly crop images from within ranger.

I know this isn't a Q&A  site, but I'd appreciate any help. Similar to this issue, I'd think my best chance to update the image preview after cropping is to try deleting the cached preview image for that specific file, before redrawing the UI.

in `rc.conf`:
```python
map x eval fm.open_console('crop ' + str(quantifier) + ' north')
```

in `commands.py`:
```python
from wand.image import Image
from ranger.api.commands import *
class crop(Command):
    def execute(self):
        # (...)
        image = str(self.fm.thisfile.basename)
        with Image(filename=image) as img:
            gravity = str(self.rest(2))
            # (...)
            img.crop(width=width, height=height, gravity=gravity)
            img.save(filename=image)
        # <-- try deleting the cached preview image somehow?
```

ps. I'm using `W3MImageDisplayer`. It is no surprise that my attempts failed, as this is my first-time python scripting... I'm not even sure which module to load. The command works fine otherwise, but I'd like to be able to immediately see how much I've cropped.

**Comment by nfnty** [comment]
Are you still having this issue on `master` with the new `scope.sh`?

**Comment by dquinton** [comment]
Ok, I finally found some time and I installed the latest master branch, 1st copied over the new scope file to my user config, and ten as further test, renamed the ranger dir in config and copied over all files from /user/local/lib... to run Ranger fresh.

Results.. After a lot of testing, its the same...  For jpeg images, I can get image preview, then toggle off preview, refresh Ranger, and get exifinfo data on the right.
For video, I get previews ok, then toggle off previews and refresh... no data shown, the video thumb is still shown, from Ranger cache.  If move to any video files not looked at, with previews toggled off, I get the mediainfo data showing OK.

Well, my thoughts... the process of Ctrl-r refresh and jumping to top of the stack is a little boring too.  Sure, there are people who prefer no previews, or there are tasks we have to do when we need the info not the preview, so we need to toggle preview off. 

Logically (and I've spent hours figuring out why its not working) the thumbnail gets cached and when preview_image is toggled on, the cached image is output... when toggled off, the mediainfo command should output to stout and the cached image is not output.  So why is the cached image still output?  The toggle should define exactly which way the video file is previewed - thumbnail or mediainfo.

Secondly, There is no indicator that preview image is toggled on or off... so how about a little image icon somewhere, like bottom-right, that displays when preview image is toggled on?

Thirdly, what about people who like having image previews ALL the time, but would like to check info about the media every so often (without the refreshing hassle) - I suggest that pressing `i` on a media file toggles an overlay of media info at the right, which disappears on key-release/ or second press. If we could set fg color/bg color/opacity of the overlay big thumbs up:)

And lastly, in scope.sh, there is no explanation about what unchecking the  
   ```  video/*)    
      #     Thumbnail
          ffmpegthumbnailer -i "${FILE_PATH}" -o "${IMAGE_CACHE_PATH}" -s 0 && exit 6    
             exit 1;; 
```
section does - ie to allow video thumbs creation.
