### ISSUE TITLE
Crash on pressing Shift + V

### ISSUE THREAD

**Issue by ppiw** [hut/ranger#433]
ranger version: 1.7.2, executed with python 3.5.0
Locale: en_US.UTF-8
Current file: /home/piotr/Downloads
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 344, in loop
    ui.handle_input()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 211, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 147, in handle_key
    self.press(key)
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 162, in press
    quantifier=keybuffer.quantifier)
  File "/usr/lib/python3.5/site-packages/ranger/core/actions.py", line 163, in execute_console
    command_name = string.lstrip().split()[0]
IndexError: list index out of range

**Comment by ppiw** [comment]
It seems that it was related with my ranger configuration. After removing ~/.config/ranger it works ok again.
