### ISSUE TITLE
solarized colorscheme

### ISSUE THREAD

**Issue by tannhuber** [hut/ranger#68]
Hello,

I modified the default colorscheme that ranger and ls output look more unique. Perhaps somebody wants to use it as well. So here it is.

```python
# Joseph Tannhuber <sepp.tannhuber@yahoo.de>, 2013
# Solarized like colorscheme, similar to solarized-dircolors
# from https://github.com/seebi/dircolors-solarized.
# This is a modification of Roman Zimbelmann's default colorscheme.
# This software is distributed under the terms of the GNU GPL version 3.

from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import *

class Solarized(ColorScheme):
    progress_bar_color = blue

    def use(self, context):
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            fg = 244
            if context.selected:
                attr = reverse
            else:
                attr = normal
            if context.empty or context.error:
                bg = red
            if context.border:
                fg = default
            if context.media:
                if context.image:
                    fg = 136
                else:
                    fg = 166
            if context.container:
                fg = 61
            if context.directory:
                fg = 33
            elif context.executable and not \
                    any((context.media, context.container,
                        context.fifo, context.socket)):
                fg = 64
                attr |= bold
            if context.socket:
                fg = 136
                bg = 230
                attr |= bold
            if context.fifo:
                fg = 136
                bg = 230
                attr |= bold
            if context.device:
                fg = 244
                bg = 230
                attr |= bold
            if context.link:
                fg = context.good and 37 or 160
                bg = context.bad and 235
                attr |= bold
            if context.tag_marker and not context.selected:
                attr |= bold
                if fg in (red, magenta):
                    fg = white
                else:
                    fg = red
            if not context.selected and (context.cut or context.copied):
                fg = 234
                attr |= bold
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    bg = 237
            if context.badinfo:
                if attr & reverse:
                    bg = magenta
                else:
                    fg = magenta

        elif context.in_titlebar:
            attr |= bold
            if context.hostname:
                fg = context.bad and 160 or 93
                bg = context.bad and 235
            elif context.directory:
                fg = 33
            elif context.tab:
                fg = context.good and 47 or 33
                bg = 239
            elif context.link:
                fg = cyan

        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = 93
                elif context.bad:
                    fg = 160
            if context.marked:
                attr |= bold | reverse
                fg = 237
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = 160
                    bg = 235
            if context.loaded:
                bg = self.progress_bar_color

        if context.text:
            if context.highlight:
                attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = 93

            if context.selected:
                attr |= reverse

            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        return fg, bg, attr
```

**Comment by redstreet** [comment]
Crashes for me as well. Not using tmux. ranger 1.5.4

The option `preview_images' was not defined in the defaults!
ranger version: 1.5.4, executed with python 2.7.3
Locale: en_US.UTF-8
Current file: /home/username/a
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 191, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 261, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 287, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 266, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 112, in draw
    self._print_result(self.result)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 276, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/curses_shortcuts.py", line 65, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python2.7/dist-packages/ranger/ext/cached_function.py", line 22, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 93, in get_attr
    fg, bg, attr = self.get(*flatten(keys))
  File "/usr/lib/python2.7/dist-packages/ranger/gui/colorscheme.py", line 75, in get
    color = self.use(context)
  File "/home/username/.config/ranger/colorschemes/solarized.py", line 107, in use
    if context.loaded:
AttributeError: 'Context' object has no attribute 'loaded'

ranger crashed.  Please report this traceback at:
http://savannah.nongnu.org/bugs/?group=ranger&func=additem

**Comment by hut** [comment]
I think we can close this since the solarized colorscheme is now part of ranger. Please open a new issue if you still have problems.
